config/routes.rb
Rails.application.routes.draw do

  get 'albums/new'

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :update, :destroy, :show] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :update, :destroy, :show]

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band

  has_many :tracks,
  dependent: :destroy

  validates :name, :band_id, presence: true
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums,
  dependent: :destroy

  has_many :tracks,
  through: :albums,
  source: :tracks,
  dependent: :destroy

  validates :name, presence: true, uniqueness: true


end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album

  validates :name, :album_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :ensure_session_token
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, uniqueness: true

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def self.generate_session_token
    SecureRandom::base64(128)
  end

  def reset_session_token!
    self.session_token ||= SecureRandom::base64(128)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::base64(128)
  end

  def is_password?(password)
    bc_obj = BCrypt::Password.new(self.password_digest)

    bc_obj.is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save!
      redirect_to band_url(@album.band)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])

    if @album.destroy
      redirect_to band_url(@album.band)
    else
      redirect_to album_url(@album)
    end
  end

  private
  def album_params
    params.require(:album).permit(:name, :recording, :band_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in_user(user)
    new_session_token = user.reset_session_token!
    session[:session_token] = new_session_token
  end

  def logged_in?
    
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save!
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])

    if @band.destroy
      redirect_to bands_url
    else
      redirect_to band_url(@band)
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(session_params[:email], session_params[:password])

    if @user
      log_in_user(@user)
      redirect_to bands_url
    end
  end

  def destroy
    if current_user
      log_out
      redirect_to new_session_url
    end
  end

  private
  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show

  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/albums/_albumcreateoredit.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
  </head>

  <body>
    <% action_url = ( action == :create ? albums_url : album_url(@album) ) %>
    <% method = (@album.persisted? ? :patch : :post) %>

    <form action="<%= action_url %>" method="post">
      <input type="hidden" name="_method" value="<%= method %>">

      <label for="album_name">Name of album</label>
      <br />
        <input type="text" id="album_name" name="album[name]"></input>
      <br />
      <br />

      <label for="band_name">Band name</label>
        <select name="album[band_id]" id="band_name">
          <% @bands.each do |band| %>
            <option value="<%= band.id %>">
            <%= band.name %></option>
          <% end %>
          debugger
        </select>
      <br />
      <br />

      <label for="recording_type">Recording Type</label>
      <br />
        <input type="radio" id="recording_type" name="album[recording]" value="live" />Live
      <br />
        <input type="radio" id="recording_type" name="album[recording]" value="studio" />Studio
      <br />
      <br />

      <input type="submit" value="<%= action == :create ? "Create new album!" : "Rename the album!" %>">
    </form>
  </body>

</html>

app/views/albums/edit.html.erb
<h1>Album Edit</h1>

<html>
<%= render "albumcreateoredit", action: :edit, album: @album %>
</html>

app/views/albums/new.html.erb
<h1>New Album Creation</h1>

<html>
<%= render "albumcreateoredit", action: :create, album: @album %>
</html>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<%= link_to "Edit Details", edit_album_url(@album) %>
<br />
<br />

<h2>Tracks</h2>
<% @album.tracks.each do |track| %>
  <p>
    <%= track.name %>
  </p>
<% end %>
<br />
<br />

<%= link_to "Add Track", tracks_url %>
<br />
<br />
<br />
<br />

<%= link_to "Delete Album", album_url(@album), method: :delete %>

app/views/bands/_band.html.erb
<%= link_to band.name, band_url(band) %>
<br />
<br />

app/views/bands/_bandcreateoredit.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
  </head>

  <body>
    <% action_url = ( action == :create ? bands_url : band_url(@band) ) %>
    <% method = (@band.persisted? ? :patch : :post) %>

    <form action="<%= action_url %>" method="post">
      <input type="hidden" name="_method" value="<%= method %>">

      <label for="band_name">Name</label>
      <br />
      <input type="text" id="band_name" name="band[name]"></input>
      <br />
      <br />
      <input type="submit" value="<%= action == :create ? "Create new band!" : "Rename the band!" %>">
    </form>
  </body>

</html>

app/views/bands/edit.html.erb
<h1>Band Edit</h1>

<html>
<%= render "bandcreateoredit", action: :edit, band: @band %>
</html>

app/views/bands/index.html.erb
<h1>Every Band In The Database</h1>

<%= render @bands %>

<br />
<br />
<%= link_to "Add New Band", new_band_url %>

app/views/bands/new.html.erb
<h1>New Band Creation</h1>

<html>
<%= render "bandcreateoredit", action: :create, band: @band %>
</html>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<%= link_to "Edit Name", edit_band_url(@band) %>
<br />
<br />

<h2>Albums</h2>
<% @band.albums.each do |album| %>
  <p>
    <%= link_to album.name, album_url(album) %>
  </p>
<% end %>
<br />
<br />

<%= link_to "Add Album", albums_new_url %>
<br />
<br />
<br />
<br />

<%= link_to "Delete Band", band_url(@band), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicAppProj</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= current_user.nil? ? "" : current_user.email %>
  <% if current_user.nil? %>
    <%= button_to 'Log In', new_session_url, method: :get %>
  <% else %>
    <%= button_to 'Log Out', session_url(current_user.id), method: :delete %>
  <% end %>
</header>

<%= yield %>

</body>

<footer>
  <br />
  <br />
  <br />
  <%= link_to "back to index", bands_url %>
</footer>
</html>

app/views/shared/_usernew.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
  </head>

  <body>
    <% action_url = ( action == :login ? sessions_url : users_url ) %>

    <form action="<%= action_url %>" method="post">
      <label for="email">Email</label>
      <br />
      <input type="text" id="email" name="user[email]"></input>
      <br />
      <br />
      <label for="password">Password</abel>
        <br />
        <input type="text" id="password" name="user[password]"></input>
        <br />
        <br />
        <input type="submit" value="<%= action == :login ? "Login" : "Sign up" %>">
      </form>
  </body>

</html>

app/views/users/new.html.erb
<h1>New User Sign Up</h1>

<html>
<%= render "shared/usernew", action: :sign_up, user: @user %>
</html>

  <!-- <%= button_to 'Sign Up!', users_url(@user), method: :create %> -->

app/views/users/show.html.erb
<h1>Profile Page</h1>

<body>
  <p>
    Your email is <%= @user.email %>
  </p>
</body>